# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactNativeOAuth2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeOAuth2
  pod 'AppAuth', '>= 0.94'

  target 'reactNativeOAuth2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactNativeOAuth2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNativeOAuth2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeOAuth2-tvOS

end
